FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y qtcreator qt5-default build-essential

COPY . /repo
WORKDIR /repo
RUN qmake
RUN make -j8
